From nginx:1.21.6

ARG MOBIOH_ROOT_WEB=/var/www/html/mobioh
ARG PATH_NGINX_CONF=/etc/nginx/conf.d/

ADD http://erp.mobioh.com.br/ultimaversao/compras_web.zip ${MOBIOH_ROOT_WEB}/

COPY default.conf ${PATH_NGINX_CONF}

RUN apt update && \
    apt -y install zip \
    unzip \
    htop \
    net-tools 
RUN unzip ${MOBIOH_ROOT_WEB}/compras_web.zip -d ${MOBIOH_ROOT_WEB}/


